spring:
  datasource:
    url: "${JDBC_DATABASE_URL:jdbc:postgresql}://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/all_extreme?serverTimezone=UTC&characterEncoding=UTF-8&sslMode=DISABLED&createDatabaseIfNotExist=true"
    username: "${JDBC_DATABASE_USERNAME:root}"
    password: "${JDBC_DATABASE_PASSWORD:1234}"
    continueOnError: true
#    driver-class-name: "com.mysql.cj.jdbc.Driver"
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 10
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  #  security:
#    oauth2:
#      client:
#        registration:
#          facebook:
#            client-id: 596493257866350
#            client-secret: 94406040e61d257c47ec385fc253dc4c
  thymeleaf:
    cache: false
    mode: HTML
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  resources:
    cache:
      cachecontrol:
        max-age: 30d
    chain:
      strategy:
        content:
          enabled: true
          paths: /css/**
cloudinary:
    cloud_name: "${CLOUD_NAME}"
    api_key: "${API_KEY}"
    api_secret: "${API_SECRET}"
allExtreme:
    clean-up: "0 0 2 ? * SUN"
server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json
  port: ${PORT:8080}
logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

